[package]
name = "macro-machines"
version = "0.2.3"
authors = ["Shane Pearman <spearman@github.com>"]
license = "MPL-2.0"

[dependencies]
# unpublished dependency version bump
colored = { version = "1.*", git = "git://github.com/mackwic/colored.git" }
escapade = "0.0.*"
log = "0.4.*"

[dev-dependencies]
simplelog = "0.5.*"
unwrap = "1.*"
