[package]
name = "macro-machines"
version = "0.8.7"
authors = ["Shane Pearman <spearman@github.com>"]
license = "MPL-2.0"
description = "State machine macros with logging and graphviz DOT file generation"
repository = "https://github.com/spearman/macro-machines"
readme = "README.md"

[dependencies]
marksman_escape = "0.1.*"
log = "0.4.*"

[dev-dependencies]
simplelog = "0.5.*"
unwrap = "1.*"
