[package]
name = "macro-machines"
version = "0.9.1"
authors = ["Shane Pearman <spearman@github.com>"]
license = "MPL-2.0"
description = "State machine macros with logging and graphviz DOT file generation"
repository = "https://github.com/spearman/macro-machines"
readme = "README.md"
edition = "2018"

[dependencies]
log = "0.4.*"
marksman_escape = "0.1.*"
variant_count = "1.*"

[dev-dependencies]
simplelog = "0.7.*"
unwrap = "1.*"
