[package]
name = "macro-machines"
version = "0.2.2"
authors = ["Shane Pearman <spearman@github.com>"]
license = "MPL-2.0"

[dependencies]
# temporary local dependency for lazy_static version bump
colored = { version = "1.*", git = "git://github.com/spearman/colored.git", branch = "bump-lazy_static" }
escapade = "0.0.*"
log = "0.4.*"

[dev-dependencies]
simplelog = "0.4.*"
unwrap = "1.*"
