[package]
name = "macro-machines"
version = "0.3.0"
authors = ["Shane Pearman <spearman@github.com>"]
license = "MPL-2.0"

[dependencies]
escapade = "0.0.*"
log = "0.4.*"

[dev-dependencies]
simplelog = "0.5.*"
unwrap = "1.*"
